# Generated by Django 4.2.14 on 2025-05-16 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoVisibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField(default=True)),
                ('nome', models.BooleanField(default=True)),
                ('sobrenome', models.BooleanField(default=True)),
                ('localidade', models.BooleanField(default=True)),
                ('telefone', models.BooleanField(default=True)),
                ('instagram', models.BooleanField(default=True)),
                ('aniversario', models.BooleanField(default=True)),
                ('profissao', models.BooleanField(default=True)),
                ('polygon', models.BooleanField(default=True)),
                ('lightining', models.BooleanField(default=True)),
                ('idade', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracao de Visibilidade',
                'verbose_name_plural': 'Configurações de Visibilidade',
            },
        ),
    ]
