# Generated by Django 4.2.14 on 2025-10-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_brl', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
