# Generated by Django 4.2.14 on 2025-10-02 00:20

from django.db import migrations

def add_valor_token(apps, schema_editor):
    administrador_acesso = apps.get_model('administrador', 'Acesso')
    if not administrador_acesso.objects.filter(link='valor_token').exists():
        acesso = administrador_acesso(nome='Valor Token', link='valor_token')
        acesso.save()
        
def remove_valor_token(apps, schema_editor):
    administrador_acesso = apps.get_model('administrador', 'Acesso')
    administrador_acesso.objects.filter(link='valor_token').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_valortoken'),
    ]

    operations = [
        migrations.RunPython(add_valor_token, remove_valor_token),
    ]
