# Generated by Django 4.2.14 on 2025-10-17 11:07

from django.db import migrations

acessos = [
    ('Adicionar Certificado', 'add_certificados'),
    ('Adicionar Pendências', 'add_pendencia'),
    ('Adicionar Pontuação', 'add'),
    ('Registrar Atividade', 'register_activity'),
    ('Lista de Usuário', 'lista_usuarios'),
    ('Log de Pontuação', 'logs')
]

def carrega_acessos_iniciais(apps, schema_editor):
    administrador_acesso = apps.get_model('administrador', 'Acesso')
    for nome, link in acessos:
        if not administrador_acesso.objects.filter(link=link).exists():
            acesso = administrador_acesso(nome=nome, link=link)
            acesso.save()
            
def remove_valor_token(apps, schema_editor):
    administrador_acesso = apps.get_model('administrador', 'Acesso')
    for _, link in acessos:
        administrador_acesso.objects.filter(link=link).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_add_valor_token'),
    ]

    operations = [
        migrations.RunPython(carrega_acessos_iniciais, remove_valor_token)
    ]
