# Generated by Django 4.2.14 on 2025-10-16 23:59

from django.db import migrations

def carregar_niveis_predefinidos(apps, schema_editor):
    """
    Carrega os níveis hierárquicos predefinidos no banco de dados.
    """
    nivel = apps.get_model('rating','Nivel')
    niveis = [
        {'nivel': 'Aprendiz', 'pontuacao_base': 0},
        {'nivel': 'Escudeiro', 'pontuacao_base': 5},
        {'nivel': 'Cavaleiro', 'pontuacao_base': 15},
        {'nivel': 'Conselheiro', 'pontuacao_base': 30},
        {'nivel': 'Guardião', 'pontuacao_base': 40},        
    ]

    id = 1
    for nivel_data in niveis:
        if not nivel.objects.filter(nivel=nivel_data['nivel']).exists():
            novo_nivel = nivel(id=id, nivel=nivel_data['nivel'], pontuacao_base=nivel_data['pontuacao_base'])
            novo_nivel.save()
            id += 1

def remover_niveis_predefinidos(apps, schema_editor):
    """
    Remove os níveis hierárquicos predefinidos do banco de dados.
    """
    Nivel = apps.get_model('rating','Nivel')
    nomes_niveis = ['Aprendiz', 'Escudeiro', 'Cavaleiro', 'Conselheiro', 'Guardião']
    Nivel.objects.filter(nome__in=nomes_niveis).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(carregar_niveis_predefinidos, remover_niveis_predefinidos),
    ]
