# Generated by Django 4.2.14 on 2025-10-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_carregar_niveis_predefinidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
