# Generated by Django 4.2.14 on 2025-07-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='hash_arquivo',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
