# Generated by Django 4.2.14 on 2025-07-22 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propostas', '0002_proposta_hash_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.BooleanField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propostas.proposta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('proposta', 'usuario')},
            },
        ),
    ]
