# Generated by Django 4.2.14 on 2025-07-22 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0003_voto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='voto',
            new_name='votos',
        ),
        migrations.AlterField(
            model_name='voto',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='propostas.proposta'),
        ),
    ]
