# Generated by Django 4.2.14 on 2025-07-30 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propostas', '0004_rename_voto_voto_votos_alter_voto_proposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to=settings.AUTH_USER_MODEL),
        ),
    ]
