# Generated by Django 4.2.14 on 2024-12-18 00:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_anuncio', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=4096)),
                ('status_anuncio', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Encerrado'), (3, 'Pausado')], default=1)),
                ('departamento', models.IntegerField(choices=[(0, 'Outros'), (1, 'Agro e indústria'), (2, 'Alimentação'), (3, 'Autos e peças'), (4, 'Eletrônicos e celulares'), (5, 'Esportes e lazer'), (6, 'Imóveis'), (7, 'Moda beleza'), (8, 'Músicas e hobbies'), (9, 'Para a sua casa'), (10, 'Prestação de serviços'), (11, 'Vagas de emprego')], default=0)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('localidade', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_loja', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=4096, null=True)),
                ('localidade', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('telefone', models.CharField(max_length=16, null=True, unique=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('web_site', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('telegram', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='lojas')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='anuncio_fotos')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='marketplace.anuncio')),
            ],
        ),
    ]
