# Generated by Django 4.2.14 on 2026-04-03 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0012_alter_profile_nivel_questionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingPeriodico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pontuacao', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10)),
                ('data', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.users')),
            ],
            options={
                'unique_together': {('user', 'tipo', 'data')},
            },
        ),
    ]
