# Generated by Django 4.2.14 on 2024-08-17 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('membro', 'Membro'), ('assessor', 'Assessor'), ('execultivo', 'Executivo'), ('lider', 'Líder'), ('diretor', 'Diretor')], default='membro', max_length=10)),
                ('pontuacao', models.IntegerField(default=0)),
                ('observacao', models.TextField(blank=True)),
                ('pendencias', models.TextField(blank=True)),
                ('squad', models.CharField(choices=[('squad_021', 'Squad 021'), ('area_51', 'Area 51'), ('curitiba', 'Curitiba'), ('serra_gaucha', 'Serra Gaucha'), ('squad_011', 'Squad 011'), ('squad_pampa', 'Squad Pampa'), ('squad_061', 'Squad 061'), ('squad_063', 'Squad 063'), ('squad_064', 'Squad 064'), ('squad_065', 'Squad 065'), ('squad_066', 'Squad 066'), ('squad_067', 'Squad 067'), ('squad_069', 'Squad 069'), ('squad_serra', 'Squad Serra')], default='squad_021', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
