# Generated by Django 4.2.14 on 2024-10-12 13:25

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rating', '__first__'),
        ('members', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePendencia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pendencia_status', models.IntegerField(choices=[(0, 'PENDENTE'), (1, 'ANDAMENTO'), (2, 'CONCLUIDA')], default=0)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('nivel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rating.nivel')),
                ('pendencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rating.pendencia')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('squad_nome', models.CharField(max_length=50)),
                ('grupo_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city', models.CharField(max_length=100)),
                ('fone', models.CharField(max_length=30)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('birth', models.DateField()),
                ('job_title', models.CharField(max_length=255)),
                ('bsc_wallet', models.CharField(blank=True, max_length=100)),
                ('lightning_wallet', models.CharField(blank=True, max_length=100)),
                ('como_conheceu', models.CharField(max_length=20)),
                ('quem_indicou', models.CharField(blank=True, max_length=100)),
                ('aonde', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pendencias',
        ),
        migrations.AddField(
            model_name='profile',
            name='nivel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rating.nivel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pic_profile',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nivel',
            field=models.CharField(choices=[('membro', 'Membro'), ('assessor', 'Assessor'), ('executivo', 'Executivo'), ('lider', 'Líder'), ('diretor', 'Diretor')], default='membro', max_length=10),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profilependencia',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='squad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='members.squad'),
        ),
    ]
