# Generated by Django 4.2.14 on 2024-10-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_profilependencia_squad_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_fraguista',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='como_conheceu',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='fone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
