# Generated by Django 4.2.14 on 2024-10-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_users_is_fraguista_alter_users_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='codigo_conduta',
            field=models.BooleanField(null=True),
        ),
    ]
