# Generated by Django 4.2.14 on 2024-12-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_profilependencia_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='lightning_wallet',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
