# Generated by Django 4.2.14 on 2025-05-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_users_lightning_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nivel',
            field=models.CharField(choices=[('aprendiz', 'Aprendiz'), ('escudeiro', 'Escudeiro'), ('cavaleiro', 'Cavaleiro'), ('conselheiro', 'Conselheiro'), ('guradiao', 'Guardião')], default='aprendiz', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilependencia',
            name='pendencia_status',
            field=models.IntegerField(choices=[(0, 'PENDENTE'), (1, 'ANDAMENTO'), (2, 'CONCLUIDA'), (3, 'REMOVIDA')], default=0),
        ),
    ]
