# Generated by Django 4.2.14 on 2025-06-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
        ('members', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nivel',
            field=models.CharField(choices=[('aprendiz', 'Aprendiz'), ('escudeiro', 'Escudeiro'), ('cavaleiro', 'Cavaleiro'), ('conselheiro', 'Conselheiro'), ('guradiao', 'Guardião'), ('nao_fraguista', 'Não Fraguista')], default='aprendiz', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilependencia',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rating.nivel'),
        ),
        migrations.AlterField(
            model_name='profilependencia',
            name='pendencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.pendencia'),
        ),
        migrations.AlterField(
            model_name='profilependencia',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.profile'),
        ),
    ]
