# Generated by Django 4.2.14 on 2025-12-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_profile_nivel_alter_profilependencia_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nivel',
            field=models.CharField(choices=[('aprendiz', 'Aprendiz'), ('escudeiro', 'Escudeiro'), ('cavaleiro', 'Cavaleiro'), ('conselheiro', 'Conselheiro'), ('guardiao', 'Guardião'), ('nao_fraguista', 'Não Fraguista')], default='aprendiz', max_length=20),
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_project', models.TextField(blank=True)),
                ('reason_to_participate', models.TextField(blank=True)),
                ('reason_to_accept', models.TextField(blank=True)),
                ('political_belief', models.TextField(blank=True)),
                ('state_opinion', models.TextField(blank=True)),
                ('jusnaturalismo_vs_juspositivismo', models.TextField(blank=True)),
                ('economic_values', models.TextField(blank=True)),
                ('bitcoin_positive_characteristics', models.TextField(blank=True)),
                ('game_theory_byzantine_generals', models.TextField(blank=True)),
                ('pna_and_argumentative_ethics', models.TextField(blank=True)),
                ('libertarian_knowledge_sources', models.TextField(blank=True)),
                ('bitcoin_knowledge_sources', models.TextField(blank=True)),
                ('contato_realizado', models.BooleanField(default=False)),
                ('contato_data', models.DateTimeField(blank=True, null=True)),
                ('contato_observacao', models.TextField(blank=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.profile')),
            ],
        ),
    ]
